name: Build and Test Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: vars
        run: |
              if [[ "$GITHUB_REF" == refs/tags/* ]]; then
              echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
              else
              echo "VERSION=latest" >> $GITHUB_ENV
              fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bodge-playwright:latest
            ghcr.io/${{ github.repository_owner }}/bodge-playwright:${{ env.VERSION }}
            mockholm/bodge-playwright:latest
            mockholm/bodge-playwright:${{ env.VERSION }}
