name: Build and Test Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      bodgeit:
        image: securecodebox/bodgeit:latest
        ports:
          - 8090:8080
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-express-playwright-app .

      - name: Run Docker container
        run: |
          docker run -d --name test-container -p 3000:3000 my-express-playwright-app

      - name: Wait for the server to start
        run: |
          sleep 10  # Wait for the server to start

    #  - name: Run tests
    #   run: |
    #     curl "http://localhost:3000/run-test?test=bodgeit-registration"  # Adjust the test name as needed

      - name: Execute bash in running container
        run: |
          docker exec test-container /bin/bash npx playwright test tests/bodgeit-registration.spec.ts --project=chromium --reporter=list

      
      - name: Stop and remove the container
        run: |
          docker stop test-container
          docker rm test-container
