name: Playwright Test Docker
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      bodgeit:
        image: securecodebox/bodgeit:latest
        ports:
          - 8090:8080
      bodge-playwright:
        image: ghcr.io/${{ github.repository_owner }}/bodge-playwright:latest
        ports:
          - 3000:3000
    steps:
    - uses: actions/checkout@v4

    - name: Wait for Bodgeit Service
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:8090; then
            echo "Bodgeit service is up!"
            break
          fi
          echo "Waiting for Bodgeit service..."
          sleep 2
        done

    - name: Run Playwright Tests
      run: |
        docker run --network host  ghcr.io/${{ github.repository_owner }}/bodge-playwright:latest bash -c "npx playwright test tests/bodgeit-registration.spec.ts --project=chromium --reporter=list"
